### ISSUE TITLE
Separate Table for Blogs?

### ISSUE THREAD

**Issue by Ishq01** [ethan-shenker/SoftDevProj0#6]
Clarify why a separate table is needed for Blogs when it seems like each user is only able to create a single blog. In that case, the columns for the Blog table can be appended to the Users table. Also, why do you need a Blog ID if each user only has 1 blog? You can just use the User ID instead/

**Comment by ethan-shenker** [comment]
we created it such that each user can create as many blogs as necessary! that's why we included a separate table for blogs.
